POST https://leme.myqnapcloud.com:60502/Auth-API.php HTTP/1.1
content-type: application/json

# {
#     "email": "admin@admin",
#     "clave": "admin1234"
# }
{
    "email": "user@user",
    "clave": "user1234"
}